CREATE TABLE doctors
(
    id          bigint primary key generated by default as identity,
    uuid        uuid unique not null,
    first_name  varchar(30) not null,
    last_name   varchar(30) not null,
    middle_name varchar(30)
);

CREATE TABLE patients
(
    id          bigint primary key generated by default as identity,
    uuid        uuid unique not null,
    first_name  varchar(30) not null,
    last_name   varchar(30) not null,
    middle_name varchar(30),
    birth_date  date        not null
);

CREATE TABLE tickets
(
    id         bigint primary key generated by default as identity,
    doctor_id  bigint references doctors (id) on delete cascade,
    patient_id bigint references patients (id) on delete cascade,
    start_time date
);

INSERT into doctors(uuid, first_name, last_name, middle_name)
values ('cdcc5ccd-9ca1-4897-95c6-9dc0766e04e4', 'Тырса', 'Николай', 'Анатольевич'),
       ('150d9b38-2b56-4e71-bf38-340e21885ffe', 'Магомед', 'Пётр', 'Иванович');

INSERT INTO patients(uuid, first_name, last_name, middle_name, birth_date)
VALUES ('6a267256-ec13-468f-b8d9-a32f87dd483d', 'Иванов', 'Иван', 'Иванович', '1993.09.15'),
       ('3de1864b-78f7-4767-a946-7c8a1c30eb9b', 'Самолётов', 'Степан', 'Алексеевич', '1998.03.15');
